### PR TITLE
[fix] Use user home directory for wallet path

### PR DESCRIPTION
**Pull request by roman-opentensor**

### CODE REVIEW

**Review by ibraheem-opentensor — APPROVED** [review]

**Comment by chad-u410** [comment]
I am having a problem that I think is related to this commit. Subnet 11, using this version, is failing to start with the following:

`KeyFileError: Keyfile at: /root/~/.bittensor/wallets/redacted/hotkeys/redacted does not exist.`

Note the `~` in the path.

If I set the environment variable BT_WALLET_PATH then it works.

**Comment by roman-opentensor** [comment]
> I am having a problem that I think is related to this commit. Subnet 11, using this version, is failing to start with the following:
> 
> `KeyFileError: Keyfile at: /root/~/.bittensor/wallets/redacted/hotkeys/redacted does not exist.`
> 
> Note the `~` in the path.
> 
> If I set the environment variable BT_WALLET_PATH then it works.

I was able to use the latest version bittensor-wallet 2.1.1.

```python
In [1]: from bittensor_wallet import Wallet

In [2]: w = Wallet()

In [3]: w.create()

IMPORTANT: Store this mnemonic in a secure (preferable offline place), as anyone who has possession of this mnemonic can use it to regenerate the key and access your tokens.

The mnemonic to the new coldkey is: material birth crush tray awake session remove quit earth broom novel staff
You can use the mnemonic to recreate the key with `btcli` in case it gets lost.
Enter your password:
Retype your password:
Encrypting...

IMPORTANT: Store this mnemonic in a secure (preferable offline place), as anyone who has possession of this mnemonic can use it to regenerate the key and access your tokens.

The mnemonic to the new hotkey is: frag*** thi** combi** square pledge reopen gas nothing margin conduct tape square
You can use the mnemonic to recreate the key with `btcli` in case it gets lost.
Out[3]: name: 'default', hotkey: 'default', path: '~/.bittensor/wallets/'

In [4]: w.coldkey_file
Out[4]: Keyfile (Py(0x14360bce0) encrypted, /Users/roman/.bittensor/wallets/default/coldkey)>

In [5]: w.hotkey_file
Out[5]: keyfile (decrypted, /Users/roman/.bittensor/wallets/default/hotkeys/default)>

In [6]: w.coldkeypub_file
Out[6]: keyfile (decrypted, /Users/roman/.bittensor/wallets/default/coldkeypub.txt)>
```

Please provide more context to help me understand what I missed.
Thank you for your comment.

**Comment by chad-u410** [comment]
Thanks so much for the reply!

I encountered this while working on subnet 11, which was upgraded yesterday. This is happening in the Validator class, roughly here: https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/neurons/validator.py#L228.

I _think_ it's related to the Config method vs WalletConfig, specifically where the Config method prepends the ~ (https://github.com/opentensor/btwallet/blob/main/src/config.rs#L42). 

In terms of reproducibility:

```
>>> from bittensor_wallet import Wallet
>>> w = Wallet()
>>> w.config()
Config(name: 'default', path: '~/~/.bittensor/wallets/', hotkey: 'default')
```

If the code from SN11 isn't correct let me know and I'll reach out to them.

Thanks!

**Comment by roman-opentensor** [comment]
> Thanks so much for the reply!
> 
> I encountered this while working on subnet 11, which was upgraded yesterday. This is happening in the Validator class, roughly here: https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/neurons/validator.py#L228.
> 
> I _think_ it's related to the Config method vs WalletConfig, specifically where the Config method prepends the ~ (https://github.com/opentensor/btwallet/blob/main/src/config.rs#L42).
> 
> In terms of reproducibility:
> 
> ```
> >>> from bittensor_wallet import Wallet
> >>> w = Wallet()
> >>> w.config()
> Config(name: 'default', path: '~/~/.bittensor/wallets/', hotkey: 'default')
> ```
> 
> If the code from SN11 isn't correct let me know and I'll reach out to them.
> 
> Thanks!

For sure. Anytime you can ask any questions. Pls feel free to do it.

And, I got you. Yep, I found this bug and fixed it in this PR https://github.com/opentensor/btwallet/pull/67

This fix will be available in the next release. 
Also, to be make sure it's working for now, pls see the next code snippet based on the code with that fix:
```python
In [1]: from bittensor_wallet import Wallet

In [2]: w = Wallet()

In [3]: w.config()
Out[3]: Config(name: 'default', path: '~/.bittensor/wallets/', hotkey: 'default')
```

**Comment by chad-u410** [comment]
Looks great, thanks again!

**Pull request merged**
